# Explorer une base de données

Exerçons nous sur Pandas. Cet exercice porte sur le dataset _chipotle.csv_ qui a été utilisé lors de la démo d'utilisation de Pandas.

1. Importez les bonnes librairies

In [1]:
import pandas as pd

2. Importez le dataset

In [2]:
dataset = pd.read_csv("../../src/chipotle.csv", index_col=0)

3. Regardez les 10 premières lignes du dataset

In [3]:
dataset.head(10)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

4. Quelle est la taille de notre dataset ?

In [4]:
dataset.shape

(4622, 5)

In [5]:
len(dataset)

4622

5. Affichez toutes les colonnes de notre dataset

In [6]:
dataset.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

6. Quel est l’item le plus commandé

     *Indice : On utilisera `.groupby()` & `sort_values()`*

In [7]:
dataset.groupby('item_name')['quantity'].sum().sort_values(ascending=False)

item_name
Chicken Bowl                             761
Chicken Burrito                          591
Chips and Guacamole                      506
Steak Burrito                            386
Canned Soft Drink                        351
Chips                                    230
Steak Bowl                               221
Bottled Water                            211
Chips and Fresh Tomato Salsa             130
Canned Soda                              126
Chicken Salad Bowl                       123
Chicken Soft Tacos                       120
Side of Chips                            110
Veggie Burrito                            97
Barbacoa Burrito                          91
Veggie Bowl                               87
Carnitas Bowl                             71
Barbacoa Bowl                             66
Carnitas Burrito                          60
Steak Soft Tacos                          56
6 Pack Soft Drink                         55
Chips and Tomatillo Red Chili Salsa       50
Chicken Crispy Tacos                      50
Chips and Tomatillo Green Chili Salsa     45
Carnitas Soft Tacos                       40
Steak Crispy Tacos                        36
Chips and Tomatillo-Green Chili Salsa     33
Steak Salad Bowl                          31
Nantucket Nectar                          29
Chips and Tomatillo-Red Chili Salsa       25
Barbacoa Soft Tacos                       25
Chips and Roasted Chili Corn Salsa        23
Izze                                      20
Chips and Roasted Chili-Corn Salsa        18
Veggie Salad Bowl                         18
Barbacoa Crispy Tacos                     12
Barbacoa Salad Bowl                       10
Chicken Salad                              9
Veggie Soft Tacos                          8
Carnitas Crispy Tacos                      8
Burrito                                    6
Carnitas Salad Bowl                        6
Veggie Salad                               6
Steak Salad                                4
Bowl                                       4
Salad                                      2
Crispy Tacos                               2
Chips and Mild Fresh Tomato Salsa          1
Veggie Crispy Tacos                        1
Carnitas Salad                             1
Name: quantity, dtype: int64

7. Combien d’items ont été commandés au total chez Chipotle

In [8]:
dataset['quantity'].sum()

4972

8. Combien de chiffre d’affaire à realisé Chipotle ?         
    A. Convertissez item_price en nombre décimal
        1. Regardez dataset[“item_price”], que voyez vous ?
        2. Trouvons un moyen d’enlever ce "$" qui nous gène. Pour cela, on peut utiliser [str](https://pandas.pydata.org/pandas-docs/stable/user_guide/text.html)
        3. Convertissons maintenant la série en float au lieu de string         
    B. Multipliez la quantité vendue par le prix de l’item   
    C. Faites la somme du tout, combien trouvez vous?       
    D. Arrondissez à deux chiffres après la virgule    
        1. On pourra utiliser la fonction __[Series.round()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.round.html#pandas.Series.round)__

In [9]:
dataset['item_price']

0        $2.39
1        $3.39
2        $3.39
3        $2.39
4       $16.98
5       $10.98
6        $1.69
7       $11.75
8        $9.25
9        $9.25
10       $4.45
11       $8.75
12       $8.75
13      $11.25
14       $4.45
15       $2.39
16       $8.49
17       $8.49
18       $2.18
19       $8.75
20       $4.45
21       $8.99
22       $3.39
23      $10.98
24       $3.39
25       $2.39
26       $8.49
27       $8.99
28       $1.09
29       $8.49
         ...
4592    $11.75
4593    $11.75
4594    $11.75
4595     $8.75
4596     $4.45
4597     $1.25
4598     $1.50
4599     $8.75
4600     $4.45
4601     $1.25
4602     $9.25
4603     $9.25
4604     $8.75
4605     $4.45
4606     $1.25
4607    $11.75
4608    $11.25
4609     $1.25
4610    $11.75
4611    $11.25
4612     $9.25
4613     $2.15
4614     $1.50
4615     $8.75
4616     $4.45
4617    $11.75
4618    $11.75
4619    $11.25
4620     $8.75
4621     $8.75
Name: item_price, Length: 4622, dtype: object

Les données dans cette colonne sont des chaines de caractères (`str`).   
Il faut les "caster" en `float` pour pouvoir les utiliser dans des calculs.

In [10]:
dataset['item_price'] = dataset['item_price'].str.replace('$', '')
dataset['item_price'] = dataset['item_price'].astype(float)

In [11]:
(dataset['item_price'] * dataset['quantity']).sum().round(2)

39237.02

9. Quel est le revenu moyen par commande ?

In [12]:
dataset["revenue"] = dataset["quantity"] * dataset["item_price"]
dataset

,order_id,quantity,item_name,choice_description,item_price,revenue
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39,2.39
1,1,1,Izze,[Clementine],3.39,3.39
2,1,1,Nantucket Nectar,[Apple],3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98,33.96
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",10.98,10.98
6,3,1,Side of Chips,NaN,1.69,1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75,11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",9.25,9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",9.25,9.25
10,5,1,Chips and Guacamole,NaN,4.45,4.45
11,6,1,Chicken Crispy Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75,8.75
12,6,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",8.75,8.75
13,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25,11.25
14,7,1,Chips and Guacamole,NaN,4.45,4.45
15,8,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39,2.39
16,8,1,Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",8.49,8.49
17,9,1,Chicken Burrito,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",8.49,8.49
18,9,2,Canned Soda,[Sprite],2.18,4.36
19,10,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",8.75,8.75
20,10,1,Chips and Guacamole,NaN,4.45,4.45
21,11,1,Barbacoa Burrito,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",8.99,8.99
22,11,1,Nantucket Nectar,[Pomegranate Cherry],3.39,3.39
23,12,1,Chicken Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Tomati...",10.98,10.98
24,12,1,Izze,[Grapefruit],3.39,3.39
25,13,1,Chips and Fresh Tomato Salsa,NaN,2.39,2.39
26,13,1,Chicken Bowl,"[Roasted Chili Corn Salsa (Medium), [Pinto Bea...",8.49,8.49
27,14,1,Carnitas Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",8.99,8.99
28,14,1,Canned Soda,[Dr. Pepper],1.09,1.09
29,15,1,Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",8.49,8.49
...,...,...,...,...,...,...
4592,1825,1,Barbacoa Burrito,"[Tomatillo Red Chili Salsa, [Rice, Fajita Vege...",11.75,11.75
4593,1825,1,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Rice, Sour Cream, ...",11.75,11.75
4594,1825,1,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Pinto Beans, Sour ...",11.75,11.75
4595,1826,1,Chicken Bowl,"[Tomatillo Green Chili Salsa, [Rice, Black Bea...",8.75,8.75
4596,1826,1,Chips and Guacamole,NaN,4.45,4.45
4597,1826,1,Canned Soft Drink,[Nestea],1.25,1.25
4598,1826,1,Bottled Water,NaN,1.50,1.50
4599,1827,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Cheese, Lettuce]]",8.75,8.75
4600,1827,1,Chips and Guacamole,NaN,4.45,4.45
4601,1827,1,Canned Soft Drink,[Diet Coke],1.25,1.25
4602,1827,1,Barbacoa Burrito,[Tomatillo Green Chili Salsa],9.25,9.25
4603,1827,1,Barbacoa Burrito,[Tomatillo Green Chili Salsa],9.25,9.25
4604,1828,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",8.75,8.75
4605,1828,1,Chips and Guacamole,NaN,4.45,4.45
4606,1828,1,Canned Soft Drink,[Coke],1.25,1.25
4607,1829,1,Steak Burrito,"[Tomatillo Green Chili Salsa, [Rice, Cheese, S...",11.75,11.75
4608,1829,1,Veggie Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25,11.25
4609,1829,1,Canned Soft Drink,[Sprite],1.25,1.25
4610,1830,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75,11.75
4611,1830,1,Veggie Burrito,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",11.25,11.25
4612,1831,1,Carnitas Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",9.25,9.25
4613,1831,1,Chips,NaN,2.15,2.15
4614,1831,1,Bottled Water,NaN,1.50,1.50
4615,1832,1,Chicken Soft Tacos,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]",8.75,8.75
4616,1832,1,Chips and Guacamole,NaN,4.45,4.45
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75,11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75,11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25,11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75,8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75,8.75

In [13]:
revenue_per_order = dataset.groupby("order_id")['revenue'].sum()
revenue_per_order

order_id
1       11.56
2       33.96
3       12.67
4       21.00
5       13.70
6       17.50
7       15.70
8       10.88
9       12.85
10      13.20
11      12.38
12      14.37
13      10.88
14      10.08
15      10.88
16      10.68
17      10.08
18      24.90
19      13.90
20      36.20
21      23.36
22      12.98
23      13.35
24      12.07
25      11.38
26      20.50
27      13.90
28      33.70
29      17.98
30      23.36
        ...
1805    20.00
1806    13.00
1807    18.64
1808    13.70
1809    14.45
1810    23.00
1811    29.25
1812    25.00
1813    35.00
1814    13.70
1815    12.50
1816    13.20
1817    13.00
1818    18.14
1819    13.20
1820    12.50
1821    13.70
1822    26.00
1823    12.15
1824    26.95
1825    66.50
1826    15.95
1827    32.95
1828    14.45
1829    24.25
1830    23.00
1831    12.90
1832    13.20
1833    23.50
1834    28.75
Name: revenue, Length: 1834, dtype: float64

In [14]:
revenue_per_order.mean()

21.394231188658654